### ISSUE TITLE
Add celebration emojis on milestone achieved

### ISSUE THREAD

**Issue by lautaropaske** [tomasellis/daily-ubi-bot#1]
As of the creation of this issue, we are at ~4325 registered humans receiving UBI. I thought it'd be cool to, for example, have the bot tweet the following when we surpass 5000 registered humans:

```
$ubi is <XX> USD right now. (-<YY>%)

🎉5000🎉  humans are receiving UBI 💧
```

Milestones could be:
- ATH price
- Multiple of 1000 registered humans achieved

**Comment by tomasellis** [comment]
I like this idea. Right now the bot isn't saving any information and I've checked CoinGecko's API and page, the API doesn't provide the ATH, but its displayed in their page so I would have to find a way to get that. On the tweet itself, I would like to display the milestone number of humans + actual humans, something like this:

```
$ubi is <XX> USD right now. (-<YY>%)

<ZZZZ> humans are receiving UBI 💧

We've reached a milestone! 🎉5000🎉 humans have registered!
```

Or something like that, what do you think?

**Comment by lautaropaske** [comment]
I like the tweet format you suggested!

We could use a JSON in the repo or similar as storage to save latest milestones. We could set the current milestones (for registered users and ATH) and save future API requests related to the subject.

I think I can implement this over the weekend 👌🏽 let me know if you'd like me to do it or if you prefer to do it yourself

**Comment by tomasellis** [comment]
For sure! I would like to see how you implement it. To clarify the bot runs once every 24hs, have fun!

**Comment by tomasellis** [comment]
We are fast approaching 5k humans! How's it going? Would you like me to try and implement it?

**Comment by lautaropaske** [comment]
hey! saw the "reached 5000🎉" tweet. good catch, community is growing fast. i haven't  found the time to do this yet but will try to tackle it this week, sorry for the delay

**Comment by tomasellis** [comment]
1/2🔋, machine. Closing this for now
